parameters:
    board_width: 100
    board_height: 30
    alien_columns: 20
    alien_rows: 5
    max_alien_projectiles: 25

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/Event/'
            - '../src/Kernel.php'
